### ISSUE TITLE
deprecated core-js 2.6.12

### ISSUE THREAD

**Issue by Muromi-Rikka** [qiniu/js-sdk#574]
core-js@2.6.12: core-js@<3.4 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.

```yaml
 /qiniu-js/3.4.0:
    dependencies:
      '@babel/runtime-corejs2': 7.18.0
 /@babel/runtime-corejs2/7.18.0:
    dependencies:
      core-js: 2.6.12
```
